server:
  port: 8080
  tomcat:
    apr:
      enabled: false

spring:
  application:
    name: sequence_monitor

  datasource:
    url: jdbc:mysql://localhost:3306/sequence_monitor
    username: ${DB_USERNAME:your_username}
    password: ${DB_PASSWORD:DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate

    show-sql: false

    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

identity:
  hash:
    secret: IDENTITY_HASH_SECRET

management:
  endpoints:
    web:
      exposure:
        include: health, info

  endpoint:
    health:
      show-details: never